services:
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
      target: development
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn workspace api dev
    ports:
      - '${API_PORT}:${API_PORT}'
    networks:
      - app-network
    environment:
      - NODE_ENV=development
      - PORT=${API_PORT}

  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      target: development
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn workspace web dev
    ports:
      - '${WEB_PORT}:3000' # NextJS runs on 3000 internally
    networks:
      - app-network
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://api:${API_PORT}

  ollama:
    build:
      context: ./apps/ollama
      dockerfile: Dockerfile
    ports:
      - "11434:11434"
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge